# Generated by Django 5.1.4 on 2025-01-29 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookapp.basemodel",
                    ),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("COD", "COD"), ("ONLINE", "ONLINE")],
                        default="COD",
                        max_length=15,
                    ),
                ),
                ("rzp_order_id", models.CharField(max_length=100, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("bookapp.basemodel",),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bookapp.basemodel",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.FloatField()),
                (
                    "book_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookapp.book"
                    ),
                ),
                (
                    "order_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderitems",
                        to="bookapp.order",
                    ),
                ),
            ],
            bases=("bookapp.basemodel",),
        ),
    ]
