# Generated by Django 5.1.4 on 2025-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
